# Generated by Django 5.2.12 on 2026-03-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.CharField(max_length=2000),
        ),
    ]
