# Generated by Django 5.2.12 on 2026-03-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortenedurl_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(max_length=2000),
        ),
    ]
