# Generated by Django 5.2.12 on 2026-03-11 20:27

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shortenedurl_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='expires_at',
            field=models.DateTimeField(default=shortener.models.get_default_expiry),
        ),
    ]
