# Generated by Django 5.2.12 on 2026-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shortenedurl_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='max_clicks',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
